language: java
  
branches:
  only:
    - master
    - stable

addons:
  postgresql: "9.6"
  apt:
    packages:
    - libmaven-ant-tasks-java
    - postgresql-9.6-postgis-2.3
    - python3
#    - python3-docutils    
    
install: true

before_script:
    - psql -c 'create database ili2db;' -U postgres
    - psql -c 'select version();' -d ili2db -U postgres
    - psql -c 'create extension postgis;' -d ili2db -U postgres
    - psql -c 'create extension "uuid-ossp";' -d ili2db -U postgres
    - psql -c 'select postgis_full_version();' -d ili2db -U postgres
    - # dpkg-query -L python3-docutils
    - python3 --version
    - python3 -m pip install docutils
    
script: 
  - ant -f build-ili2pg.xml jar 
  - ant -f build-ili2pg.xml junit -Ddburl=jdbc:postgresql:ili2db -Ddbusr=postgres 
  - ant -f build-ili2pg.xml  junitreport
  - # ant -f build-ili2pg.xml -Dpython=python -Drst2html=/usr/share/docutils/python3/scripts/rst2html usrdoc 
  - python3 -m rst2html doc/ili2db.rst doc/ili2db.html
after_success:
  - python travis/html2text.py  build/test-out/junit-noframes.html
after_failure:
  - python travis/html2text.py  build/test-out/junit-noframes.html
deploy:
  - provider: script
    skip_cleanup: true
    script: ant -Duser.repos_pwd=${repos_pwd} -Duser.repos_usr=jql_jars-INTE -f build-ili2pg.xml  bindist deploy
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ant -Duser.repos_pwd=${repos_pwd} -Duser.repos_usr=jql_jars-INTE -Drelease=final -f build-ili2pg.xml bindist deploy
    on:
      branch: stable
notifications:
  email:
    recipients:
      - ce@eisenhutinformatik.ch
    on_success: change # default: change
    on_failure: always # default: always